# Generated by Django 3.2 on 2021-06-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0002_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='phone_no',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
