# Generated by Django 3.2 on 2021-06-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0003_auto_20210611_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('dob', models.DateField(null=True)),
            ],
        ),
    ]
