# Generated by Django 3.2 on 2021-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0005_victim'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
