# Generated by Django 3.2 on 2021-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0006_auto_20210618_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIR_Title', models.CharField(max_length=100, null=True)),
                ('FIR_Type', models.CharField(max_length=100, null=True)),
                ('Victim_Name', models.CharField(max_length=50, null=True)),
                ('Victim_Age', models.CharField(max_length=2, null=True)),
                ('Victim_Address', models.CharField(max_length=100, null=True)),
                ('FIR_Description', models.TextField(null=True)),
                ('FIR_Date', models.DateField(null=True)),
                ('Incident_Time', models.TimeField()),
                ('Incident_Place', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
